"""Visualizador de barras elétricas georreferenciadas."""

from .circuit_colors import (
    contrast_ratio_with_white,
    generate_circuit_palette,
    normalize_hex_color,
)
from .branch_analysis import (
    BranchAnalysisResult,
    BranchIssue,
    BranchRecord,
    BranchType,
    analyze_branches,
)
from .equivalent_network import (
    EquivalentLoadPatternRecord,
    EquivalentLoadRecord,
    EquivalentNetworkIssue,
    EquivalentNetworkModel,
    EquivalentNetworkResult,
    EquivalentVisibilityMasks,
    build_equivalent_network,
)
from .model import (
    BarRecord,
    CircuitCatalogModel,
    CircuitDefinition,
    CircuitMembership,
    Bounds,
    CircuitModel,
    CircuitVisibilityController,
    FeatureSelection,
    LineNetworkModel,
    LoadModel,
    LoadPatternModel,
    LoadPatternRecord,
    LoadRecord,
    NetworkTopology,
    SegmentRecord,
    StaticPointIndex,
    StaticSegmentIndex,
    SwitchModel,
    SwitchRecord,
    UtmCrs,
)
from .phase_config import (
    PHASE_COLORS,
    UNMAPPED_PHASE_COLOR,
    PhaseClassification,
    PhaseConfiguration,
    PhaseConfigurationError,
    PhaseMappingEntry,
    default_phase_configuration_path,
    load_phase_configuration,
)
from .load_import import LoadCsvResult, LoadIssue, load_loads_csv
from .load_pattern_import import (
    LoadPatternCsvResult,
    LoadPatternIssue,
    load_load_patterns_csv,
)
from .search import (
    FieldSearchPartition,
    FieldSearchSnapshot,
    GlobalSearchIndex,
    SearchCancelled,
    SearchFieldMatch,
    SearchMode,
    SearchQueryResult,
    SearchResult,
    build_field_search_partition,
    normalize_code,
    query_field_snapshot,
)

__all__ = [
    "analyze_branches",
    "build_equivalent_network",
    "BarRecord",
    "BranchAnalysisResult",
    "BranchIssue",
    "BranchRecord",
    "BranchType",
    "CircuitCatalogModel",
    "CircuitDefinition",
    "CircuitMembership",
    "Bounds",
    "CircuitModel",
    "CircuitVisibilityController",
    "contrast_ratio_with_white",
    "FeatureSelection",
    "EquivalentLoadPatternRecord",
    "EquivalentLoadRecord",
    "EquivalentNetworkIssue",
    "EquivalentNetworkModel",
    "EquivalentNetworkResult",
    "EquivalentVisibilityMasks",
    "generate_circuit_palette",
    "FieldSearchPartition",
    "FieldSearchSnapshot",
    "GlobalSearchIndex",
    "LineNetworkModel",
    "LoadCsvResult",
    "LoadIssue",
    "LoadModel",
    "LoadPatternCsvResult",
    "LoadPatternIssue",
    "LoadPatternModel",
    "LoadPatternRecord",
    "LoadRecord",
    "load_load_patterns_csv",
    "load_loads_csv",
    "NetworkTopology",
    "normalize_hex_color",
    "normalize_code",
    "PHASE_COLORS",
    "PhaseClassification",
    "PhaseConfiguration",
    "PhaseConfigurationError",
    "PhaseMappingEntry",
    "default_phase_configuration_path",
    "load_phase_configuration",
    "SearchCancelled",
    "SearchFieldMatch",
    "SearchMode",
    "SearchQueryResult",
    "SearchResult",
    "build_field_search_partition",
    "query_field_snapshot",
    "SegmentRecord",
    "StaticPointIndex",
    "StaticSegmentIndex",
    "SwitchModel",
    "SwitchRecord",
    "UtmCrs",
    "UNMAPPED_PHASE_COLOR",
]

__version__ = "0.1.0"
